### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/TodoMVC#1]
Hi Dominik!
TodoMVC app is not working. JavaScript version crashes during startup and CoffeeScript version is missing ./meteor/packages.

**Comment by rhyslbw** [comment]
Thanks for reporting this. We've been moving really quick with a major development push, and didn't have any tests for this particular example to stop regression. We'd already have this fixed, but are both in limited mode this weekend. Will get it sorted ASAP

**Comment by rhyslbw** [comment]
@darko-mijic This has been fixed. We're working on a testing API that will be implemented here as it evolves to cover the objects like Space.flux.Store, so keep watching this repo if that peaks your interest. Thanks again, hope you like what you see with Space

**Comment by rhyslbw** [comment]
Hey @darko-mijic. Any chance you'd be up for a chat in our [Gitter room](https://gitter.im/meteor-space/general)?

**Comment by darko-mijic** [comment]
Hey @rhyslbw. I have joined the room.
