### ISSUE TITLE
Shall we drop coffeescript version of this app - voting now open 

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/TodoMVC#3]
nay or aye?

**Comment by rhyslbw** [comment]
Given we'll have to drop CS class support in the near future I think we can shed this weight now. I vote for dropping the example

**Comment by darko-mijic** [comment]
I agree with Rhys if CS class support will be dropped in the near future. 
If not this is our only CS sample app and sample apps are really useful for testing API changes.

**Comment by darko-mijic** [comment]
@DominikGuzei and @qejk?

**Comment by DominikGuzei** [comment]
Yeah i guess it will be the simplest path to only have _one_ official way to define and use `Space.Object` based classes. This is the most flexible path for the future compared to supporting CS / ES6 `class` statements, that cannot be "upgraded" in interesting ways. So let's drop the CS example.

**Comment by qejk** [comment]
I agree. However we should somewhere point out in readme - that having Space related class definitions don't need to be "ugly" like JS ones in CS (since most CS users just hate curly brackets/parentheses polluting code with nonsense everywhere) Still even tho using CS - don't knowing about tricks like this:

```
Donations.App = Space.Application.define 'Donations.App', 
  #do stuff
```

```
Space.messaging.define Space.messaging.Command, `Donations`, 
  CreateOrganization: 
    adminId: Guid,
    name: String,
    country: Country,
    contact: Donations.Contact

```

etc...

**Comment by DominikGuzei** [comment]
Yeah we can also rewrite it to use `Space.Object.extend` etc. with CS
